# Generated by Django 5.0.6 on 2024-07-25 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_remove_post_comments_alter_post_content_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='repost',
            field=models.ManyToManyField(blank=True, related_name='comment_repost', to=settings.AUTH_USER_MODEL),
        ),
    ]
