# Generated by Django 5.0.6 on 2024-07-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_remove_comment_post_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comments',
        ),
    ]
