# Generated by Django 5.0.6 on 2024-07-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
