# Generated by Django 5.0.6 on 2024-07-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_remove_comment_is_active_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.post'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
