# Generated by Django 5.0.6 on 2024-08-01 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_post_original_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
